/* Designed, brandable resume — renders the same profile/job/match data as a
   styled one-pager (inline CSS, system fonts, indigo accent, print-friendly),
   then hands it to the browser's print dialog so the user can "Save as PDF".
   Dependency-free: no canvas, no PDF lib — the browser does the rendering. */

import type { CareerProfile, JobMatch, JobPosting } from "../types";
import { buildResume } from "./applyKit";

const ACCENT = "#4f46e5";
const INK = "#111827";
const MUT = "#6b7280";
const LINE = "#e5e7eb";

/** A brandable accent override — future-proof seam for per-company branding. */
export interface ResumeBrand {
  accent?: string;
  fontFamily?: string;
}

/** Parsed resume sections: the header block plus ALL-CAPS sections with items. */
export interface ResumeSections {
  header: string[];
  sections: { title: string; items: string[] }[];
}

/** Parse the plain-text resume template into sections for styled rendering.
    Shared by the HTML one-pager and the pdf-lib renderer. */
export function parseResumeSections(text: string): ResumeSections {
  const lines = text.split("\n");
  const header: string[] = [];
  const sections: { title: string; items: string[] }[] = [];
  let cur: { title: string; items: string[] } | null = null;
  for (const raw of lines) {
    const t = raw.trim();
    if (t && t === t.toUpperCase() && t.length > 2 && /^[A-Z0-9 .•·+&#-]+$/.test(t)) {
      cur = { title: t, items: [] };
      sections.push(cur);
    } else if (cur && t) {
      cur.items.push(t);
    } else if (!cur && t) {
      header.push(t);
    }
  }
  return { header, sections };
}

export function buildResumeHtml(
  profile: CareerProfile,
  job: JobPosting,
  match: JobMatch | null,
  brand: ResumeBrand = {},
  textOverride?: string
): string {
  const accent = brand.accent ?? ACCENT;
  const font = brand.fontFamily ?? "'Segoe UI', -apple-system, 'Helvetica Neue', Arial, sans-serif";
  const text = textOverride ?? buildResume(profile, job, match);
  const { header, sections } = parseResumeSections(text);

  const esc = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const headerBlock = header.length
    ? `
        <div class="header">
          <div class="name">${esc(header[0] || profile.headline || job.title)}</div>
          <div class="sub">${esc(header.slice(1).join(" · "))}</div>
        </div>`
    : "";
  const body = headerBlock + sections.map(sec => {
    return `
      <section>
        <h2>${esc(sec.title)}</h2>
        <ul>${sec.items.map(i => `<li>${esc(i.replace(/^•\s*/, ""))}</li>`).join("")}</ul>
      </section>`;
  }).join("");

  const meta = `${esc([profile.location, profile.workAuth].filter(Boolean).join(" · "))}`;

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<title>${esc(profile.headline || job.title)} — ${esc(job.company)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: ${font}; color: ${INK}; background: #fff; line-height: 1.5; }
  .page { max-width: 720px; margin: 0 auto; padding: 48px 56px; }
  .header { border-bottom: 3px solid ${accent}; padding-bottom: 16px; margin-bottom: 22px; }
  .name { font-size: 26px; font-weight: 800; letter-spacing: -0.02em; }
  .sub { margin-top: 4px; font-size: 13px; color: ${MUT}; }
  section { margin-bottom: 20px; }
  h2 { font-size: 12px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase;
       color: ${accent}; border-bottom: 1px solid ${LINE}; padding-bottom: 4px; margin-bottom: 8px; }
  ul { list-style: none; }
  li { font-size: 13px; color: ${INK}; margin-bottom: 5px; padding-left: 14px; position: relative; }
  li::before { content: "▸"; position: absolute; left: 0; color: ${accent}; font-size: 11px; top: 1px; }
  .meta { font-size: 12px; color: ${MUT}; margin-top: 2px; }
  @media print {
    body { padding: 0; }
    .page { padding: 24px 40px; }
  }
</style></head>
<body><div class="page">
  ${body}
  <div class="meta">Generated by InterviewIQ · tailored to ${esc(job.company)} · ${meta}</div>
</div>
<script>window.onload = function () { setTimeout(function () { window.print(); }, 300); };</script>
</body></html>`;
}

/** Opens the designed resume in a new window and triggers the print dialog
    ("Save as PDF"). Returns false if the popup was blocked. */
export function openResumePrint(profile: CareerProfile, job: JobPosting, match: JobMatch | null, brand: ResumeBrand = {}, textOverride?: string): boolean {
  const html = buildResumeHtml(profile, job, match, brand, textOverride);
  const w = window.open("", "_blank", "width=860,height=1100");
  if (!w) return false;
  w.document.open();
  w.document.write(html);
  w.document.close();
  return true;
}
