/* One-click styled PDF resume — built with pdf-lib (the app's only PDF
   authoring dependency; the reader stays pdfjs-dist). Renders the same
   parsed sections as the HTML one-pager: bold name, accent rule, section
   headers in the accent color, wrapped bullets. Downloads directly —
   no print dialog, works fully offline. */

import { PDFDocument, PDFFont, StandardFonts, rgb, type RGB } from "pdf-lib";
import type { CareerProfile, JobMatch, JobPosting } from "../types";
import { buildResume } from "./applyKit";
import { parseResumeSections, type ResumeBrand } from "./resumeHtml";

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 56;
const CONTENT_W = PAGE_W - 2 * MARGIN;

function hexToRgb(hex: string): RGB {
  const h = hex.replace("#", "");
  const n = parseInt(h.length === 3 ? h.split("").map(c => c + c).join("") : h, 16);
  return rgb(((n >> 16) & 0xff) / 255, ((n >> 8) & 0xff) / 255, (n & 0xff) / 255);
}

function wrap(font: PDFFont, size: number, text: string, maxWidth: number): string[] {
  const words = text.split(" ");
  const out: string[] = [];
  let line = "";
  for (const w of words) {
    const probe = line ? line + " " + w : w;
    if (font.widthOfTextAtSize(probe, size) > maxWidth && line) {
      out.push(line);
      line = w;
    } else {
      line = probe;
    }
  }
  if (line) out.push(line);
  return out;
}

export async function renderResumePdf(
  profile: CareerProfile,
  job: JobPosting,
  match: JobMatch | null,
  brand: ResumeBrand = {}
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.addPage([PAGE_W, PAGE_H]);
  const accent = hexToRgb(brand.accent ?? "#4f46e5");
  const ink = rgb(0.07, 0.09, 0.15);
  const mut = rgb(0.42, 0.45, 0.52);

  const { header, sections } = parseResumeSections(buildResume(profile, job, match));
  let current = page;
  let y = PAGE_H - MARGIN - 8;

  const newPage = (): void => {
    current = pdf.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - MARGIN - 8;
  };

  /* header block */
  if (header.length) {
    const name = header[0] || profile.headline || job.title;
    current.drawText(name, { x: MARGIN, y, size: 24, font: bold, color: ink });
    y -= 20;
    if (header.length > 1) {
      const sub = header.slice(1).join(" · ");
      for (const line of wrap(font, 10, sub, CONTENT_W)) {
        current.drawText(line, { x: MARGIN, y, size: 10, font, color: mut });
        y -= 14;
      }
    }
    y -= 8;
    current.drawRectangle({ x: MARGIN, y, width: CONTENT_W, height: 2.5, color: accent });
    y -= 18;
  }

  const drawSection = (title: string, items: string[]) => {
    if (y < 70) newPage();
    current.drawText(title.toUpperCase(), { x: MARGIN, y, size: 11, font: bold, color: accent });
    y -= 16;
    current.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.8, color: rgb(0.9, 0.91, 0.93) });
    y -= 10;
    for (const raw of items) {
      const text = raw.replace(/^•\s*/, "");
      const lines = wrap(font, 10, text, CONTENT_W - 12);
      for (const line of lines) {
        if (y < 56) newPage();
        /* bullet glyph + text (WinAnsi-safe bullet) */
        current.drawText("\u2022", { x: MARGIN, y: y - 1, size: 9, font, color: accent });
        current.drawText(line, { x: MARGIN + 12, y, size: 10, font, color: ink });
        y -= 14;
      }
      y -= 2;
    }
    y -= 6;
  };

  for (const sec of sections) drawSection(sec.title, sec.items);

  /* footer meta */
  const footer = `Generated by InterviewIQ · tailored to ${job.company}`;
  current.drawText(footer, { x: MARGIN, y: 34, size: 8, font, color: mut });

  return pdf.save();
}

/** One-click download of the styled resume PDF. */
export async function downloadResumePdf(
  profile: CareerProfile,
  job: JobPosting,
  match: JobMatch | null,
  brand: ResumeBrand = {}
): Promise<void> {
  const bytes = await renderResumePdf(profile, job, match, brand);
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `resume-${job.company}-${job.title.replace(/[^\w-]+/g, "-")}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
