/* Export — renders roadmap as markdown and downloads it */

import { companyById, fieldById, GENERAL_COMPANY, levelById } from "../../data";
import type { Priority, Roadmap } from "./types";

const PRIORITY_ICON: Record<Priority, string> = { P0: "🔴", P1: "🟡", P2: "🟢" };

/** Renders the roadmap as portable markdown (weeks, priorities, resources). */
export function exportRoadmapMarkdown(roadmap: Roadmap): string {
  const g = roadmap.goal;
  const company = companyById(g.companyId);
  const field = fieldById(g.fieldId);
  const lines: string[] = [];
  lines.push(`# 🧭 InterviewIQ Career Roadmap`);
  lines.push(``);
  lines.push(`**${levelById(g.currentLevel).name} → ${levelById(g.targetLevel).name}** · ${field?.name ?? ""}${company.id !== GENERAL_COMPANY.id ? ` · ${company.name}` : ""} · target ${g.targetDate} · ${g.hoursPerWeek}h/week`);
  lines.push(``);
  lines.push(`> ${roadmap.summary}`);
  if (g.jdKeywords?.length) lines.push(`> 📋 Tailored from a job description — ${g.jdKeywords.length} keyword topics.`);
  lines.push(``);

  const all = roadmap.weeks.flatMap(w => w.topics);
  const done = all.filter(t => t.done).length;
  const p0 = all.filter(t => t.priority === "P0" && !t.done).length;
  lines.push(`## Progress`);
  lines.push(`- ${done}/${all.length} topics done · ${p0} P0 remaining · ${roadmap.weeks.filter(w => w.status === "done").length}/${roadmap.weeks.length} weeks done`);
  lines.push(``);

  for (const w of roadmap.weeks) {
    const badge = w.status === "done" ? "✅ " : w.status === "current" ? "🔥 " : "";
    lines.push(`## ${badge}Week ${w.week} — ${w.phaseLabel} (${w.start} → ${w.end})`);
    lines.push(`> ${w.goal}`);
    lines.push(``);
    for (const t of w.topics) {
      const mark = t.done ? "- [x]" : "- [ ]";
      const res = t.info.links.map(l => `[${l.label}](${l.url})`).join(" · ");
      lines.push(`${mark} ${PRIORITY_ICON[t.priority]} **${t.label}** (~${t.estHours}h)${t.statusNote ? ` — ${t.statusNote}` : ""}`);
      lines.push(`    ${t.info.primer}`);
      if (res) lines.push(`    Resources: ${res}`);
    }
    lines.push(``);
  }

  const gp = roadmap.weeks.flatMap(w => w.topics).filter(t => t.practice);
  if (gp.length) {
    lines.push(`## Practice questions`);
    for (const t of gp.slice(0, 12)) {
      if (t.practice) lines.push(`- **${t.label}** — ${t.practice.q}`);
    }
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(`Generated by InterviewIQ · ${new Date().toISOString().slice(0, 10)}`);
  return lines.join("\n");
}

/** Downloads the roadmap as a .md file. */
export function downloadRoadmapMarkdown(roadmap: Roadmap): void {
  const md = exportRoadmapMarkdown(roadmap);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `interviewiq-roadmap-${roadmap.goal.targetDate || "plan"}.md`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
