/* AUTO-GENERATED by scripts/ai-draft-problems.js — do not edit by hand.
   P4 AI-authored coding problems (docs/question-bank-expansion.md §4).
   Every problem below passed its own visible + hidden cases through the local
   judge before being written. Prompts, test cases and references are
   AI-ORIGINAL; titles, difficulty and companies come from public problem-title
   metadata (facts). Generated 2026-08-17T00:00:00.000Z. */

import type { CliProblem } from "../coding";

export const AI_GENERATED_PROBLEMS: CliProblem[] = [
];

/* Generated problem id → company ids (facts from the mirror metadata). */
export const AI_PROBLEM_COMPANIES: Record<string, string[]> = {
};

/* Generated problem id → CLI topic bucket (company frequency + roadmap). */
export const AI_CLI_TOPICS: Record<string, string> = {
};
